---
abstract: 'store HTTP crawl results for later consumption'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Crawl-Store
no_index:
  directory:
    - t
    - inc
requires:
  App::scrape: '0'
  Carp: '0'
  DBD::SQLite: '1.62'
  DBIx::RunSQL: '0'
  Digest: '0'
  Digest::SHA: '0'
  Encode: '0'
  File::ShareDir: '0'
  File::ShareDir::Install: '0'
  Filter::signatures: '0.09'
  HTTP::Headers: '0'
  HTTP::Request: '0'
  HTTP::Response: '0'
  JSON::XS: '0'
  Minion: '0'
  Minion::Backend::SQLite: '0'
  Mojolicious: '0'
  Moo: '2'
  POSIX: '0'
  Path::Class: '0'
  Scalar::Util: '0'
  Time::Local: '0'
  URI: '0'
  YAML::Tiny: '0'
  charnames: '0'
  perl: '5.008'
resources:
  repository: git://github.com/Corion/HTTP-Crawl-Store.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
